### ISSUE TITLE
0.12.x support

### ISSUE THREAD

**Issue by niftylettuce** [hrz-unimr/node-qrc#2]

**Comment by rolinh** [comment]
I proposed my 0.12.x port [here](https://github.com/hrz-unimr/node-qrc/pull/1#issuecomment-125481671) but got no answer so far.

@niftylettuce If you are interested in a 0.12.x version, you can consider [node-qrcodeine](https://github.com/NetOxygen/node-qrcodeine), which is available [here](https://www.npmjs.com/package/qrcodeine).

**Comment by niftylettuce** [comment]
@Rolinh having trouble installing it on OS X 10.9, maybe due to XCode?

``` log
  CXX(target) Release/obj.target/qrcodeine/src/qrcodeine.o
../src/qrcodeine.cc:11:10: fatal error: 'qrencode.h' file not found
#include <qrencode.h>
```

**Comment by rolinh** [comment]
@niftylettuce Because you're missing the [libqrencode](http://fukuchi.org/works/qrencode/) dependency.

**Comment by tmuellerleile** [comment]
Hi,

@niftylettuce: Sorry for a very late answer on this, but @Rolinh was perfectly right: As 0.12 is not supported by qrc at the moment, you should simply use [node-qrcodeine](https://github.com/NetOxygen/node-qrcodeine).

@Rolinh: As I am writing this, I actually noticed missing your generous offer for creating another PR for adding 0.12 compatibility – thank you very(!) much and sorry for not answering at all... :disappointed: However as the waves in node/io development have calmed, I would like to take some time and have a look at providing support for 4.0.0, the first common stable release.
